spring:
  application:
    name: gestao_vagas
  main:
    banner-mode: off
  datasource:
    username: user
    password: user123
    url: jdbc:postgresql://localhost:5432/gestao_vagas
  jpa:
    hibernate:
      ddl-auto: update
