version: '3.9'

services:
  postgres:
    container_name: 'gestao_vagas'
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=gestao_vagas
